<a href="https://colab.research.google.com/github/Code-RED-LionKing/Likelion-Jejubase/blob/main/Numpy_Pandas_0523.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# random/ 순열/ 표준편차/ 분산
# Pandas


In [ ]:
import numpy as np

a = np.random.rand(2, 2) #0 ~ 1 사이값 랜덤.
print(a)

[[0.86638622 0.78298856]
 [0.80757177 0.72307364]]


In [ ]:
b  = np.random.randn(2, 2) # 평균이 0, 분산이1: 표준정규분포
print(b)

[[ 0.44528967 -1.29533961]
 [-0.97856777  1.24622148]]


In [ ]:
c = np.random.randint(0 ,10, size=5)
print(c)


[4 4 4 9 8]


In [ ]:
c2 = np.random.randint(0, 10, size=(2,2))
print(c2)

[[2 5]
 [3 0]]


In [ ]:
d = np.arange(5)
d_shuffle = np.random.shuffle(d) # 원본 값이 변한다. print(d_shuffle)가 안됨. 변한값이 복사가 안된다.
print(d)

[4 3 1 0 2]


In [ ]:
choice = np.random.choice(2, 5) #중복 허용
print(choice)

choice = np.random.choice(5, 3, replace= False) #replace=False #중복 허용 x
print(choice) 

choice = np.random.choice(d, 5, replace = False)
print(choice)

choice = np.random.choice(d, 5, p=[0, 0.2, 0.2, 0.1, 0.5])# =p = []지정확률 

[1 1 0 1 1]
[4 1 0]
[3 0 4 2 1]


In [ ]:
# permutation 순열

a = np.arange(10)
print(a)
a_p = np.random.permutation(a)
print(a_p)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 2 1 8 9 0 7 6 4 3]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#정규분포를 따르는 난수 생성
#a = np.random.normal('평균', '표준편차', '갯수')
a = np.random.normal(0, 1, 3)
print(a)

[-1.01962851 -1.05952141 -0.43800501]


## pandas

In [ ]:
import pandas as pd


#series

In [ ]:
data =[1, 2, 3, 4, 5]
index = ['a', 'b' ,'c' ,'d','e']
series = pd.Series(data, index=index) # 활용
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
series[:4]

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
print(series >4 )

print(series[series > 2])

a    False
b    False
c    False
d    False
e     True
dtype: bool
c    3
d    4
e    5
dtype: int64


In [ ]:
print(series[series < 5])

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
print(series + 100)
print(series - 100)
print(series * 100)
print(series ** 100)
print(series / 100)
print(series % 100)
print(series // 100)

a    101
b    102
c    103
d    104
e    105
dtype: int64
a   -99
b   -98
c   -97
d   -96
e   -95
dtype: int64
a    100
b    200
c    300
d    400
e    500
dtype: int64
a                      1
b                      0
c   -2984622845537545263
d                      0
e   -3842938066129721103
dtype: int64
a    0.01
b    0.02
c    0.03
d    0.04
e    0.05
dtype: float64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    0
b    0
c    0
d    0
e    0
dtype: int64


## Series 객체에 접근

In [ ]:
print(series.keys)

<bound method Series.keys of a    1
b    2
c    3
d    4
e    5
dtype: int64>


In [ ]:
print(series.values)

[1 2 3 4 5]


In [ ]:
s2 = pd.Series({'a':1, 'b':2,'c':3, 'd':4})
print(s2.keys)

<bound method Series.keys of a    1
b    2
c    3
d    4
dtype: int64>


In [ ]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

# items



In [ ]:
print(s2.items())

In [ ]:
for index, value in s2.items():
  print(f'인덱스: {index}, 데이터: {value}')

인덱스: a, 데이터: 1
인덱스: b, 데이터: 2
인덱스: c, 데이터: 3
인덱스: d, 데이터: 4


In [ ]:
s = pd.Series([10, 20, 30, 40], index = ['a','b','c','d'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [ ]:
print(s.loc['b']) #loc: 행에 접근
print(s.loc['b':'d'])

20
b    20
c    30
d    40
dtype: int64


In [ ]:
print(s.iloc) # 열 접근
print(s.iloc[2])
print(s.iloc[-1])#-1번째 인덱스값
print(s.iloc[1:3])#1번째 ~2번쨰 인덱스값



30
40
b    20
c    30
dtype: int64


In [ ]:
print(s.at['a']) 
print(s.iat[1])

10
20


In [ ]:
print(s.get('e')) # 없는 값에 대한 처리 .get('')

None


## 결측값 (NaN, None)

Nan(Not a Number)

- isna()
- isnull()


In [ ]:
data = [1, 2, 3, None]

print(np.array(data))
print(pd.Series(data))

[1 2 3 None]
0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


In [108]:
s = pd.Series(data)

print(s.isna())
print(s.isnull())

0    False
1    False
2    False
3     True
dtype: bool
0    False
1    False
2    False
3     True
dtype: bool


In [110]:
print((s.isna().sum()))

1


In [111]:
print(s.notnull().sum())

3


### 결측치 제거

In [113]:
s.dropna() # Nan 값제거

0    1.0
1    2.0
2    3.0
dtype: float64

In [114]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [121]:
s.fillna(0)


0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

In [119]:
s.fillna(1)

0    1.0
1    2.0
2    3.0
3    1.0
dtype: float64

# series 함수

In [122]:
s = pd.Series([1,3,5,7,9])
s.count()

5

In [123]:
s.min()
s.max()

9

In [125]:
print(s.mean())
print(s.median())
print(s.std())
print(s.var())

5.0
5.0
3.1622776601683795
10.0


In [126]:
s.describe()

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64