# Numpy


In [1]:
import numpy as np

In [8]:
a = np.array([1, 2, 3, 4])
print(a) #행렬에서의 1차원 배열

[1 2 3 4]


In [9]:
l = [1, 2, 3, 4]
print(l)

[1, 2, 3, 4]


In [10]:
print(a. shape)
print(a. ndim)
print(a.dtype)

(4,)
1
int32


In [23]:
b = np.array([[1,2,3], [2,3,3],[3,4,3]])
print(b)

print(b)
print(b. shape)
print(b. ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

[[1 2 3]
 [2 3 3]
 [3 4 3]]
[[1 2 3]
 [2 3 3]
 [3 4 3]]
(4,)
1
int32
4
36


In [25]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(c)
print(c. shape)
print(c. ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(4,)
1
int32
4
36


In [27]:
# 1차원: 벡터

v = np.array([1,2,3])
print(v)

[1 2 3]


In [29]:
# 2차원 : 행렬(Matrix
m = np.array([[1,2,3], [1,2,3]])
print(m)

[[1 2 3]
 [1 2 3]]


In [30]:
#3차원 : 텐서(Tensor)


In [32]:
f = np.array([i for i in range(0, 10, 2)]) #(start, end, step)
print(f)
print(f. shape)
print(f. ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
(5,)
1
int32
4
20


In [37]:
c = np.array([1 + 2j, 3 +4j, 5 + 6j], dtype=np.complex64)
print(c)
print(c.real # 실수부분 출력
print(c.imag) # 허수부분 출력
      

[1.+2.j 3.+4.j 5.+6.j]
[1. 3. 5.]
[2. 4. 6.]


# 문자형


In [40]:
data = [1, 2, 3]
s = np.string_(data)
print(s)
print(s.dtype)

b'\x01\x02\x03'
|S3


In [43]:
data3 = [1,2,3,4,5]
print(data3)

s2 = np.string_(data3) #  s2 =np.array(data3, dtype = 'S')
print(s2)
print(s2.dtype)

[1, 2, 3, 4, 5]
b'\x01\x02\x03\x04\x05'
|S5


### 유니코드

In [44]:
u = np.array(data3, dtype = 'U') # 유니코드

print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


## 데이터 형 변환(Cast, Casting 형 변환)

In [45]:
data = [1.1, 2 , 3]
a = np.float64(data) #np.데이터타입
print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [49]:
a = a.astype(np.int64)
print(a)
print(a.dtype)

[1 2 3]
int64


In [51]:
b = np.uint16(0)
print(b)
print(b.dtype)

0
uint16


In [52]:
c= np.uint16(-1) # uint ( 0 ~ 65,535)
print(c)

65535
